title: Tristan Montoya, PhD
email: tristan.montoya@alumni.utoronto.ca
email_secondary: tristan.montoya@usask.ca
description: Tristan Montoya, Computational Scientist
css_version: "20260224-1"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tjbmontoya.com/"
github_username: tristanmontoya
profile_picture: profile.jpeg
institute_url: https://www.mi.uni-koeln.de/NumSim/

# Build settings
plugins:
  - jekyll-seo-tag

collections:
  papers:
    output: true
    permalink: /:collection/:name
  conferences:
    output: true
    permalink: /:collection/:name
  preprints:
    output: true
    permalink: /:collection/:name
  thesis:
    output: true
    permalink: /:collection/:name
  talks:
    output: true
    permalink: /:collection/:name
